### ISSUE TITLE
Missing required packages xkeyval & xparse

### ISSUE THREAD

**Issue by LordFckHelmchen** [9999years/latex-changelog#1]
Dear Karin,
I am getting a lot of errors ([see log](https://github.com/9999years/latex-changelog/files/3047477/main.log)) when compiling [this minimal example](https://github.com/9999years/latex-changelog/files/3047483/main.txt) (txt just to enable GitHub upload) using the following setup:
- Ubuntu 16.4 
- TexStudio
- TexLive2018
- Compile command `pdflatex -synctex=1 -interaction=nonstopmode -output-directory=build %.tex`)

I believe these are caused by missing required package directives for xkeyval & xparse. Or at least adding 
```
\RequirePackage{xkeyval}
\RequirePackage{xparse}
```
to line 11 & 12 of changelog.sty fixed the errors.

Greetings, David

**Comment by 9999years** [comment]
Hm, that’s fixed in the repo (https://github.com/9999years/latex-changelog/blob/master/changelog.sty#L8) but not live on CTAN, it seems. I’ll get a fix uploaded soon.

**Comment by 9999years** [comment]
Looks like documentation needs updating, too. I’ll try to have this fixed in a week or two.
