### ISSUE TITLE
Move xkeyval to l3keys

### ISSUE THREAD

**Issue by pablgonz** [9999years/latex-changelog#2]
Hello, since you are using `xparse/expl3`, because it does not move the system `key = val` to `l3keys`, it is equal or more powerful and you do not have to use external packages.
Saludos

**Comment by 9999years** [comment]
Thanks for the report! xparse is part of l3packages and very common, so I’m
not too worried about the dependency. However, if you’d like to open a pull
request, I’ll seriously consider merging it.
