### ISSUE TITLE
LaTeX Warning: Label `sec:changelog' multiply defined.

### ISSUE THREAD

**Issue by TagoriaTar** [9999years/latex-changelog#25]
At our company we work at a bigger project and we have different changelog for differenct document chapters (by topic for each contributor). Due to the fact that changelog itself creates an label, our log print out a lot of warnings "Label `sec:changelog' multiply defined." Let the user create the label itself, not by the package, or at least provide an option to deactivade the automatic generation of labels.

**Comment by 9999years** [comment]
> Let the user create the label itself, not by the package

Use `\begin{changelog}[section=false] ... \end{changelog}` to disable automatic generation of the section and associated label (you will need to add your own `\section` if you desire one). Alternatively, use `\begin{changelog}[label=my-unique-label]` to choose a non-conflicting label.

This is all [documented in the user manual](http://mirrors.ctan.org/macros/latex/contrib/changelog/changelog.pdf) in section 3 ("The `changelog` environment") on page 3.

**Comment by 9999years** [comment]
> Just a hint, that the automatic creation of the associated label is also disabled, is **not** written in the manual.

Yeah, sorry, maybe that was unclear: `\label`s are only meaningful if they're attached to a `\section` or figure or whatnot, so it doesn't make sense to generate them if there's no `\section` being generated.

I've clarified the documentation and released version 2.6.0, which lets you set `label=` to skip generating a label entirely. It should be live on CTAN in ~24 hrs.
